/*
 * Copyright (c) 2017. 联思智云（北京）科技有限公司. All rights reserved.
 */
/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.smartsuites.interpreter.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-11-26")
public class RemoteInterpreterContext implements org.apache.thrift.TBase<RemoteInterpreterContext, RemoteInterpreterContext._Fields>, java.io.Serializable, Cloneable, Comparable<RemoteInterpreterContext> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RemoteInterpreterContext");

  private static final org.apache.thrift.protocol.TField NOTE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("noteId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PARAGRAPH_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("paragraphId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField REPL_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("replName", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField PARAGRAPH_TITLE_FIELD_DESC = new org.apache.thrift.protocol.TField("paragraphTitle", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField PARAGRAPH_TEXT_FIELD_DESC = new org.apache.thrift.protocol.TField("paragraphText", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField AUTHENTICATION_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("authenticationInfo", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField CONFIG_FIELD_DESC = new org.apache.thrift.protocol.TField("config", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField GUI_FIELD_DESC = new org.apache.thrift.protocol.TField("gui", org.apache.thrift.protocol.TType.STRING, (short)8);
  private static final org.apache.thrift.protocol.TField RUNNERS_FIELD_DESC = new org.apache.thrift.protocol.TField("runners", org.apache.thrift.protocol.TType.STRING, (short)9);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RemoteInterpreterContextStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RemoteInterpreterContextTupleSchemeFactory();

  public java.lang.String noteId; // required
  public java.lang.String paragraphId; // required
  public java.lang.String replName; // required
  public java.lang.String paragraphTitle; // required
  public java.lang.String paragraphText; // required
  public java.lang.String authenticationInfo; // required
  public java.lang.String config; // required
  public java.lang.String gui; // required
  public java.lang.String runners; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NOTE_ID((short)1, "noteId"),
    PARAGRAPH_ID((short)2, "paragraphId"),
    REPL_NAME((short)3, "replName"),
    PARAGRAPH_TITLE((short)4, "paragraphTitle"),
    PARAGRAPH_TEXT((short)5, "paragraphText"),
    AUTHENTICATION_INFO((short)6, "authenticationInfo"),
    CONFIG((short)7, "config"),
    GUI((short)8, "gui"),
    RUNNERS((short)9, "runners");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NOTE_ID
          return NOTE_ID;
        case 2: // PARAGRAPH_ID
          return PARAGRAPH_ID;
        case 3: // REPL_NAME
          return REPL_NAME;
        case 4: // PARAGRAPH_TITLE
          return PARAGRAPH_TITLE;
        case 5: // PARAGRAPH_TEXT
          return PARAGRAPH_TEXT;
        case 6: // AUTHENTICATION_INFO
          return AUTHENTICATION_INFO;
        case 7: // CONFIG
          return CONFIG;
        case 8: // GUI
          return GUI;
        case 9: // RUNNERS
          return RUNNERS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NOTE_ID, new org.apache.thrift.meta_data.FieldMetaData("noteId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PARAGRAPH_ID, new org.apache.thrift.meta_data.FieldMetaData("paragraphId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.REPL_NAME, new org.apache.thrift.meta_data.FieldMetaData("replName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PARAGRAPH_TITLE, new org.apache.thrift.meta_data.FieldMetaData("paragraphTitle", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PARAGRAPH_TEXT, new org.apache.thrift.meta_data.FieldMetaData("paragraphText", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.AUTHENTICATION_INFO, new org.apache.thrift.meta_data.FieldMetaData("authenticationInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CONFIG, new org.apache.thrift.meta_data.FieldMetaData("config", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.GUI, new org.apache.thrift.meta_data.FieldMetaData("gui", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.RUNNERS, new org.apache.thrift.meta_data.FieldMetaData("runners", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RemoteInterpreterContext.class, metaDataMap);
  }

  public RemoteInterpreterContext() {
  }

  public RemoteInterpreterContext(
    java.lang.String noteId,
    java.lang.String paragraphId,
    java.lang.String replName,
    java.lang.String paragraphTitle,
    java.lang.String paragraphText,
    java.lang.String authenticationInfo,
    java.lang.String config,
    java.lang.String gui,
    java.lang.String runners)
  {
    this();
    this.noteId = noteId;
    this.paragraphId = paragraphId;
    this.replName = replName;
    this.paragraphTitle = paragraphTitle;
    this.paragraphText = paragraphText;
    this.authenticationInfo = authenticationInfo;
    this.config = config;
    this.gui = gui;
    this.runners = runners;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RemoteInterpreterContext(RemoteInterpreterContext other) {
    if (other.isSetNoteId()) {
      this.noteId = other.noteId;
    }
    if (other.isSetParagraphId()) {
      this.paragraphId = other.paragraphId;
    }
    if (other.isSetReplName()) {
      this.replName = other.replName;
    }
    if (other.isSetParagraphTitle()) {
      this.paragraphTitle = other.paragraphTitle;
    }
    if (other.isSetParagraphText()) {
      this.paragraphText = other.paragraphText;
    }
    if (other.isSetAuthenticationInfo()) {
      this.authenticationInfo = other.authenticationInfo;
    }
    if (other.isSetConfig()) {
      this.config = other.config;
    }
    if (other.isSetGui()) {
      this.gui = other.gui;
    }
    if (other.isSetRunners()) {
      this.runners = other.runners;
    }
  }

  public RemoteInterpreterContext deepCopy() {
    return new RemoteInterpreterContext(this);
  }

  @Override
  public void clear() {
    this.noteId = null;
    this.paragraphId = null;
    this.replName = null;
    this.paragraphTitle = null;
    this.paragraphText = null;
    this.authenticationInfo = null;
    this.config = null;
    this.gui = null;
    this.runners = null;
  }

  public java.lang.String getNoteId() {
    return this.noteId;
  }

  public RemoteInterpreterContext setNoteId(java.lang.String noteId) {
    this.noteId = noteId;
    return this;
  }

  public void unsetNoteId() {
    this.noteId = null;
  }

  /** Returns true if field noteId is set (has been assigned a value) and false otherwise */
  public boolean isSetNoteId() {
    return this.noteId != null;
  }

  public void setNoteIdIsSet(boolean value) {
    if (!value) {
      this.noteId = null;
    }
  }

  public java.lang.String getParagraphId() {
    return this.paragraphId;
  }

  public RemoteInterpreterContext setParagraphId(java.lang.String paragraphId) {
    this.paragraphId = paragraphId;
    return this;
  }

  public void unsetParagraphId() {
    this.paragraphId = null;
  }

  /** Returns true if field paragraphId is set (has been assigned a value) and false otherwise */
  public boolean isSetParagraphId() {
    return this.paragraphId != null;
  }

  public void setParagraphIdIsSet(boolean value) {
    if (!value) {
      this.paragraphId = null;
    }
  }

  public java.lang.String getReplName() {
    return this.replName;
  }

  public RemoteInterpreterContext setReplName(java.lang.String replName) {
    this.replName = replName;
    return this;
  }

  public void unsetReplName() {
    this.replName = null;
  }

  /** Returns true if field replName is set (has been assigned a value) and false otherwise */
  public boolean isSetReplName() {
    return this.replName != null;
  }

  public void setReplNameIsSet(boolean value) {
    if (!value) {
      this.replName = null;
    }
  }

  public java.lang.String getParagraphTitle() {
    return this.paragraphTitle;
  }

  public RemoteInterpreterContext setParagraphTitle(java.lang.String paragraphTitle) {
    this.paragraphTitle = paragraphTitle;
    return this;
  }

  public void unsetParagraphTitle() {
    this.paragraphTitle = null;
  }

  /** Returns true if field paragraphTitle is set (has been assigned a value) and false otherwise */
  public boolean isSetParagraphTitle() {
    return this.paragraphTitle != null;
  }

  public void setParagraphTitleIsSet(boolean value) {
    if (!value) {
      this.paragraphTitle = null;
    }
  }

  public java.lang.String getParagraphText() {
    return this.paragraphText;
  }

  public RemoteInterpreterContext setParagraphText(java.lang.String paragraphText) {
    this.paragraphText = paragraphText;
    return this;
  }

  public void unsetParagraphText() {
    this.paragraphText = null;
  }

  /** Returns true if field paragraphText is set (has been assigned a value) and false otherwise */
  public boolean isSetParagraphText() {
    return this.paragraphText != null;
  }

  public void setParagraphTextIsSet(boolean value) {
    if (!value) {
      this.paragraphText = null;
    }
  }

  public java.lang.String getAuthenticationInfo() {
    return this.authenticationInfo;
  }

  public RemoteInterpreterContext setAuthenticationInfo(java.lang.String authenticationInfo) {
    this.authenticationInfo = authenticationInfo;
    return this;
  }

  public void unsetAuthenticationInfo() {
    this.authenticationInfo = null;
  }

  /** Returns true if field authenticationInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetAuthenticationInfo() {
    return this.authenticationInfo != null;
  }

  public void setAuthenticationInfoIsSet(boolean value) {
    if (!value) {
      this.authenticationInfo = null;
    }
  }

  public java.lang.String getConfig() {
    return this.config;
  }

  public RemoteInterpreterContext setConfig(java.lang.String config) {
    this.config = config;
    return this;
  }

  public void unsetConfig() {
    this.config = null;
  }

  /** Returns true if field config is set (has been assigned a value) and false otherwise */
  public boolean isSetConfig() {
    return this.config != null;
  }

  public void setConfigIsSet(boolean value) {
    if (!value) {
      this.config = null;
    }
  }

  public java.lang.String getGui() {
    return this.gui;
  }

  public RemoteInterpreterContext setGui(java.lang.String gui) {
    this.gui = gui;
    return this;
  }

  public void unsetGui() {
    this.gui = null;
  }

  /** Returns true if field gui is set (has been assigned a value) and false otherwise */
  public boolean isSetGui() {
    return this.gui != null;
  }

  public void setGuiIsSet(boolean value) {
    if (!value) {
      this.gui = null;
    }
  }

  public java.lang.String getRunners() {
    return this.runners;
  }

  public RemoteInterpreterContext setRunners(java.lang.String runners) {
    this.runners = runners;
    return this;
  }

  public void unsetRunners() {
    this.runners = null;
  }

  /** Returns true if field runners is set (has been assigned a value) and false otherwise */
  public boolean isSetRunners() {
    return this.runners != null;
  }

  public void setRunnersIsSet(boolean value) {
    if (!value) {
      this.runners = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case NOTE_ID:
      if (value == null) {
        unsetNoteId();
      } else {
        setNoteId((java.lang.String)value);
      }
      break;

    case PARAGRAPH_ID:
      if (value == null) {
        unsetParagraphId();
      } else {
        setParagraphId((java.lang.String)value);
      }
      break;

    case REPL_NAME:
      if (value == null) {
        unsetReplName();
      } else {
        setReplName((java.lang.String)value);
      }
      break;

    case PARAGRAPH_TITLE:
      if (value == null) {
        unsetParagraphTitle();
      } else {
        setParagraphTitle((java.lang.String)value);
      }
      break;

    case PARAGRAPH_TEXT:
      if (value == null) {
        unsetParagraphText();
      } else {
        setParagraphText((java.lang.String)value);
      }
      break;

    case AUTHENTICATION_INFO:
      if (value == null) {
        unsetAuthenticationInfo();
      } else {
        setAuthenticationInfo((java.lang.String)value);
      }
      break;

    case CONFIG:
      if (value == null) {
        unsetConfig();
      } else {
        setConfig((java.lang.String)value);
      }
      break;

    case GUI:
      if (value == null) {
        unsetGui();
      } else {
        setGui((java.lang.String)value);
      }
      break;

    case RUNNERS:
      if (value == null) {
        unsetRunners();
      } else {
        setRunners((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case NOTE_ID:
      return getNoteId();

    case PARAGRAPH_ID:
      return getParagraphId();

    case REPL_NAME:
      return getReplName();

    case PARAGRAPH_TITLE:
      return getParagraphTitle();

    case PARAGRAPH_TEXT:
      return getParagraphText();

    case AUTHENTICATION_INFO:
      return getAuthenticationInfo();

    case CONFIG:
      return getConfig();

    case GUI:
      return getGui();

    case RUNNERS:
      return getRunners();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case NOTE_ID:
      return isSetNoteId();
    case PARAGRAPH_ID:
      return isSetParagraphId();
    case REPL_NAME:
      return isSetReplName();
    case PARAGRAPH_TITLE:
      return isSetParagraphTitle();
    case PARAGRAPH_TEXT:
      return isSetParagraphText();
    case AUTHENTICATION_INFO:
      return isSetAuthenticationInfo();
    case CONFIG:
      return isSetConfig();
    case GUI:
      return isSetGui();
    case RUNNERS:
      return isSetRunners();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof RemoteInterpreterContext)
      return this.equals((RemoteInterpreterContext)that);
    return false;
  }

  public boolean equals(RemoteInterpreterContext that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_noteId = true && this.isSetNoteId();
    boolean that_present_noteId = true && that.isSetNoteId();
    if (this_present_noteId || that_present_noteId) {
      if (!(this_present_noteId && that_present_noteId))
        return false;
      if (!this.noteId.equals(that.noteId))
        return false;
    }

    boolean this_present_paragraphId = true && this.isSetParagraphId();
    boolean that_present_paragraphId = true && that.isSetParagraphId();
    if (this_present_paragraphId || that_present_paragraphId) {
      if (!(this_present_paragraphId && that_present_paragraphId))
        return false;
      if (!this.paragraphId.equals(that.paragraphId))
        return false;
    }

    boolean this_present_replName = true && this.isSetReplName();
    boolean that_present_replName = true && that.isSetReplName();
    if (this_present_replName || that_present_replName) {
      if (!(this_present_replName && that_present_replName))
        return false;
      if (!this.replName.equals(that.replName))
        return false;
    }

    boolean this_present_paragraphTitle = true && this.isSetParagraphTitle();
    boolean that_present_paragraphTitle = true && that.isSetParagraphTitle();
    if (this_present_paragraphTitle || that_present_paragraphTitle) {
      if (!(this_present_paragraphTitle && that_present_paragraphTitle))
        return false;
      if (!this.paragraphTitle.equals(that.paragraphTitle))
        return false;
    }

    boolean this_present_paragraphText = true && this.isSetParagraphText();
    boolean that_present_paragraphText = true && that.isSetParagraphText();
    if (this_present_paragraphText || that_present_paragraphText) {
      if (!(this_present_paragraphText && that_present_paragraphText))
        return false;
      if (!this.paragraphText.equals(that.paragraphText))
        return false;
    }

    boolean this_present_authenticationInfo = true && this.isSetAuthenticationInfo();
    boolean that_present_authenticationInfo = true && that.isSetAuthenticationInfo();
    if (this_present_authenticationInfo || that_present_authenticationInfo) {
      if (!(this_present_authenticationInfo && that_present_authenticationInfo))
        return false;
      if (!this.authenticationInfo.equals(that.authenticationInfo))
        return false;
    }

    boolean this_present_config = true && this.isSetConfig();
    boolean that_present_config = true && that.isSetConfig();
    if (this_present_config || that_present_config) {
      if (!(this_present_config && that_present_config))
        return false;
      if (!this.config.equals(that.config))
        return false;
    }

    boolean this_present_gui = true && this.isSetGui();
    boolean that_present_gui = true && that.isSetGui();
    if (this_present_gui || that_present_gui) {
      if (!(this_present_gui && that_present_gui))
        return false;
      if (!this.gui.equals(that.gui))
        return false;
    }

    boolean this_present_runners = true && this.isSetRunners();
    boolean that_present_runners = true && that.isSetRunners();
    if (this_present_runners || that_present_runners) {
      if (!(this_present_runners && that_present_runners))
        return false;
      if (!this.runners.equals(that.runners))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetNoteId()) ? 131071 : 524287);
    if (isSetNoteId())
      hashCode = hashCode * 8191 + noteId.hashCode();

    hashCode = hashCode * 8191 + ((isSetParagraphId()) ? 131071 : 524287);
    if (isSetParagraphId())
      hashCode = hashCode * 8191 + paragraphId.hashCode();

    hashCode = hashCode * 8191 + ((isSetReplName()) ? 131071 : 524287);
    if (isSetReplName())
      hashCode = hashCode * 8191 + replName.hashCode();

    hashCode = hashCode * 8191 + ((isSetParagraphTitle()) ? 131071 : 524287);
    if (isSetParagraphTitle())
      hashCode = hashCode * 8191 + paragraphTitle.hashCode();

    hashCode = hashCode * 8191 + ((isSetParagraphText()) ? 131071 : 524287);
    if (isSetParagraphText())
      hashCode = hashCode * 8191 + paragraphText.hashCode();

    hashCode = hashCode * 8191 + ((isSetAuthenticationInfo()) ? 131071 : 524287);
    if (isSetAuthenticationInfo())
      hashCode = hashCode * 8191 + authenticationInfo.hashCode();

    hashCode = hashCode * 8191 + ((isSetConfig()) ? 131071 : 524287);
    if (isSetConfig())
      hashCode = hashCode * 8191 + config.hashCode();

    hashCode = hashCode * 8191 + ((isSetGui()) ? 131071 : 524287);
    if (isSetGui())
      hashCode = hashCode * 8191 + gui.hashCode();

    hashCode = hashCode * 8191 + ((isSetRunners()) ? 131071 : 524287);
    if (isSetRunners())
      hashCode = hashCode * 8191 + runners.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(RemoteInterpreterContext other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetNoteId()).compareTo(other.isSetNoteId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNoteId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.noteId, other.noteId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetParagraphId()).compareTo(other.isSetParagraphId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParagraphId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.paragraphId, other.paragraphId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetReplName()).compareTo(other.isSetReplName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReplName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.replName, other.replName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetParagraphTitle()).compareTo(other.isSetParagraphTitle());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParagraphTitle()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.paragraphTitle, other.paragraphTitle);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetParagraphText()).compareTo(other.isSetParagraphText());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParagraphText()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.paragraphText, other.paragraphText);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetAuthenticationInfo()).compareTo(other.isSetAuthenticationInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAuthenticationInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.authenticationInfo, other.authenticationInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetConfig()).compareTo(other.isSetConfig());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetConfig()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.config, other.config);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetGui()).compareTo(other.isSetGui());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGui()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.gui, other.gui);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetRunners()).compareTo(other.isSetRunners());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRunners()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.runners, other.runners);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RemoteInterpreterContext(");
    boolean first = true;

    sb.append("noteId:");
    if (this.noteId == null) {
      sb.append("null");
    } else {
      sb.append(this.noteId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("paragraphId:");
    if (this.paragraphId == null) {
      sb.append("null");
    } else {
      sb.append(this.paragraphId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("replName:");
    if (this.replName == null) {
      sb.append("null");
    } else {
      sb.append(this.replName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("paragraphTitle:");
    if (this.paragraphTitle == null) {
      sb.append("null");
    } else {
      sb.append(this.paragraphTitle);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("paragraphText:");
    if (this.paragraphText == null) {
      sb.append("null");
    } else {
      sb.append(this.paragraphText);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("authenticationInfo:");
    if (this.authenticationInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.authenticationInfo);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("config:");
    if (this.config == null) {
      sb.append("null");
    } else {
      sb.append(this.config);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("gui:");
    if (this.gui == null) {
      sb.append("null");
    } else {
      sb.append(this.gui);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("runners:");
    if (this.runners == null) {
      sb.append("null");
    } else {
      sb.append(this.runners);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RemoteInterpreterContextStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RemoteInterpreterContextStandardScheme getScheme() {
      return new RemoteInterpreterContextStandardScheme();
    }
  }

  private static class RemoteInterpreterContextStandardScheme extends org.apache.thrift.scheme.StandardScheme<RemoteInterpreterContext> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RemoteInterpreterContext struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NOTE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.noteId = iprot.readString();
              struct.setNoteIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PARAGRAPH_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.paragraphId = iprot.readString();
              struct.setParagraphIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // REPL_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.replName = iprot.readString();
              struct.setReplNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PARAGRAPH_TITLE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.paragraphTitle = iprot.readString();
              struct.setParagraphTitleIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // PARAGRAPH_TEXT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.paragraphText = iprot.readString();
              struct.setParagraphTextIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // AUTHENTICATION_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.authenticationInfo = iprot.readString();
              struct.setAuthenticationInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // CONFIG
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.config = iprot.readString();
              struct.setConfigIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // GUI
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.gui = iprot.readString();
              struct.setGuiIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // RUNNERS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.runners = iprot.readString();
              struct.setRunnersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RemoteInterpreterContext struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.noteId != null) {
        oprot.writeFieldBegin(NOTE_ID_FIELD_DESC);
        oprot.writeString(struct.noteId);
        oprot.writeFieldEnd();
      }
      if (struct.paragraphId != null) {
        oprot.writeFieldBegin(PARAGRAPH_ID_FIELD_DESC);
        oprot.writeString(struct.paragraphId);
        oprot.writeFieldEnd();
      }
      if (struct.replName != null) {
        oprot.writeFieldBegin(REPL_NAME_FIELD_DESC);
        oprot.writeString(struct.replName);
        oprot.writeFieldEnd();
      }
      if (struct.paragraphTitle != null) {
        oprot.writeFieldBegin(PARAGRAPH_TITLE_FIELD_DESC);
        oprot.writeString(struct.paragraphTitle);
        oprot.writeFieldEnd();
      }
      if (struct.paragraphText != null) {
        oprot.writeFieldBegin(PARAGRAPH_TEXT_FIELD_DESC);
        oprot.writeString(struct.paragraphText);
        oprot.writeFieldEnd();
      }
      if (struct.authenticationInfo != null) {
        oprot.writeFieldBegin(AUTHENTICATION_INFO_FIELD_DESC);
        oprot.writeString(struct.authenticationInfo);
        oprot.writeFieldEnd();
      }
      if (struct.config != null) {
        oprot.writeFieldBegin(CONFIG_FIELD_DESC);
        oprot.writeString(struct.config);
        oprot.writeFieldEnd();
      }
      if (struct.gui != null) {
        oprot.writeFieldBegin(GUI_FIELD_DESC);
        oprot.writeString(struct.gui);
        oprot.writeFieldEnd();
      }
      if (struct.runners != null) {
        oprot.writeFieldBegin(RUNNERS_FIELD_DESC);
        oprot.writeString(struct.runners);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RemoteInterpreterContextTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RemoteInterpreterContextTupleScheme getScheme() {
      return new RemoteInterpreterContextTupleScheme();
    }
  }

  private static class RemoteInterpreterContextTupleScheme extends org.apache.thrift.scheme.TupleScheme<RemoteInterpreterContext> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RemoteInterpreterContext struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetNoteId()) {
        optionals.set(0);
      }
      if (struct.isSetParagraphId()) {
        optionals.set(1);
      }
      if (struct.isSetReplName()) {
        optionals.set(2);
      }
      if (struct.isSetParagraphTitle()) {
        optionals.set(3);
      }
      if (struct.isSetParagraphText()) {
        optionals.set(4);
      }
      if (struct.isSetAuthenticationInfo()) {
        optionals.set(5);
      }
      if (struct.isSetConfig()) {
        optionals.set(6);
      }
      if (struct.isSetGui()) {
        optionals.set(7);
      }
      if (struct.isSetRunners()) {
        optionals.set(8);
      }
      oprot.writeBitSet(optionals, 9);
      if (struct.isSetNoteId()) {
        oprot.writeString(struct.noteId);
      }
      if (struct.isSetParagraphId()) {
        oprot.writeString(struct.paragraphId);
      }
      if (struct.isSetReplName()) {
        oprot.writeString(struct.replName);
      }
      if (struct.isSetParagraphTitle()) {
        oprot.writeString(struct.paragraphTitle);
      }
      if (struct.isSetParagraphText()) {
        oprot.writeString(struct.paragraphText);
      }
      if (struct.isSetAuthenticationInfo()) {
        oprot.writeString(struct.authenticationInfo);
      }
      if (struct.isSetConfig()) {
        oprot.writeString(struct.config);
      }
      if (struct.isSetGui()) {
        oprot.writeString(struct.gui);
      }
      if (struct.isSetRunners()) {
        oprot.writeString(struct.runners);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RemoteInterpreterContext struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(9);
      if (incoming.get(0)) {
        struct.noteId = iprot.readString();
        struct.setNoteIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.paragraphId = iprot.readString();
        struct.setParagraphIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.replName = iprot.readString();
        struct.setReplNameIsSet(true);
      }
      if (incoming.get(3)) {
        struct.paragraphTitle = iprot.readString();
        struct.setParagraphTitleIsSet(true);
      }
      if (incoming.get(4)) {
        struct.paragraphText = iprot.readString();
        struct.setParagraphTextIsSet(true);
      }
      if (incoming.get(5)) {
        struct.authenticationInfo = iprot.readString();
        struct.setAuthenticationInfoIsSet(true);
      }
      if (incoming.get(6)) {
        struct.config = iprot.readString();
        struct.setConfigIsSet(true);
      }
      if (incoming.get(7)) {
        struct.gui = iprot.readString();
        struct.setGuiIsSet(true);
      }
      if (incoming.get(8)) {
        struct.runners = iprot.readString();
        struct.setRunnersIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

